language: python
python:
  - 3.4.3
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly

install:
- pip install --upgrade pip
- pip install -r requirements-dev.txt
- pip install codecov

script:
- make coverage

after_success:
- codecov

env:
  matrix:
  - PYTHONASYNCIODEBUG=x
  - PYTHONASYNCIODEBUG=
